---
version: 2
before:
  hooks:
    - go mod tidy
    - git diff --exit-code go.mod go.sum
builds:
  - main: ./cmd/gg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - formats: ['binary']

changelog:
  sort: asc

brews:
  - name: gg
    directory: Formula
    repository:
      owner: joakimen
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    dependencies:
      - name: gh
