# .lefthook.yaml
---
pre-commit:
  parallel: true
  jobs:
    - name: go
      group:
        jobs:
          - run: go fmt ./...
          - run: goimports -w .
          - run: staticcheck ./...
          - run: go vet ./...
    - name: md-lint
      glob: "*.md"
      run: markdownlint {staged_files} --disable MD013
    - name: yaml-lint
      glob: "*.{yml,yaml}"
      exclude:
        - .golangci.yml
      run: yamllint {staged_files}
    - name: json-lint
      glob: "*.json"
      run: jsonlint {staged_files} --check
