---
quiet: false
disable-version-string: true
with-expecter: true
all: true
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
dir: "mocks"
outpkg: "mocks"
packages:
  github.com/joakimen/gg/github:
  github.com/joakimen/gg/keyring:
  github.com/joakimen/gg:
