---
version: "3"

vars:
  GOBIN:
    sh: |
      if [ -z "$(go env GOBIN)" ]; then
        echo "$(go env GOPATH)/bin"
      else
        echo "$(go env GOBIN)"
      fi
  BIN: ./bin/gg
  MAINPRG: ./cmd/gg

tasks:
  default:
    desc: Default task (all)
    cmds:
      - task: all

  all:
    desc: Run all build steps
    cmds:
      - task: fmt
      - task: lint
      - task: build
      - task: test

  help:
    desc: Display this help
    cmds:
      - task --list

  fmt:
    desc: Format Go code
    cmds:
      - gofumpt -l -w .
      - goimports -w .

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - staticcheck ./...

  build:
    desc: Build the application
    cmds:
      - go build -o {{.BIN}} {{.MAINPRG}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  init:
    desc: Initialize the project
    cmds:
      - task: install-tools

  install-tools:
    desc: Install Go tools
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest

  release:
    desc: Create a new release tag
    preconditions:
      - sh: command -v svu >/dev/null 2>&1
        msg: "svu is not installed. Please install it first."
    cmds:
      - |
        next_tag=$(svu next)
        git tag $next_tag
        echo "git tag $next_tag"
      - git push --tags

  mock:
    desc: Generate mocks
    cmds:
      - mockery

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN}} ./dist
