---
name: ci

# yamllint disable-line rule:truthy
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: go - setup
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: go - install tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: go - lint
        run: |
          go vet ./...
          staticcheck ./...

      - name: release by tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_JOAKIMEN_HOMEBREW_TAP }}
